### ISSUE TITLE
Support for i3 spin

### ISSUE THREAD

**Issue by Henry-Hiles** [risiIndustries/risiOS-meta#1]
An i3 spin of this would be great, just the fedora i3 spin with the extra risi tweaks and scripts.

**Comment by PizzaLovingNerd** [comment]
I do not plan on supporting any other DE at the moment because of the fact that there's features in risiTweaks built specifically around GNOME and I don't have time to support any other DEs. I would be interested in making spins in the distance future, but I would need a bigger development team before I did so. For now, GNOME will be the only option.

**Comment by Henry-Hiles** [comment]
I see. Thanks.

**Comment by PizzaLovingNerd** [comment]
Thanks for understanding
